GODOT ?= /Applications/Godot_mono.app/Contents/MacOS/Godot

GOD_V1_PATH := v1-canuter-3d-tps
GOD_V2_PATH := v2-iso3d
GOD_V3_PATH := v3-iso3d-targeting
GOD_V4_PATH := v4-iso3d-moba-like
GOD_V5_PATH := v5-character-prototype
GOD_V6_PATH := v6-character-prototype
GOD_V7_PATH := v7-fps-prototype
GOD_V8_PATH := v8-fps-prototype
GOD_V9_PATH := v9-space-survival-prototype
GOD_V10_PATH := v10-doom-wall-lab
GOD_V11_PATH := v11-house-comparison
GOD_V12_PATH := v12-voxel-cross-corridor
GOD_V13_PATH := v13-preprocessed-voxel-runtime
GOD_V14_PATH := v14-ramp-voxel-runtime

.PHONY: \
	run-v1 \
	run-v2 \
	run-v3 \
	run-v4 \
	run-v5 \
	run-v6 \
	run-v7 \
	run-v8 \
	run-v9 \
	run-v10 \
	run-v11 \
	run-v12 \
	run-v13 \
	run-v14

run-v1:
	"$(GODOT)" --path "$(GOD_V1_PATH)"

run-v2:
	"$(GODOT)" --path "$(GOD_V2_PATH)"

run-v3:
	"$(GODOT)" --path "$(GOD_V3_PATH)"

run-v4:
	"$(GODOT)" --path "$(GOD_V4_PATH)"

run-v5:
	"$(GODOT)" --path "$(GOD_V5_PATH)"

run-v6:
	"$(GODOT)" --path "$(GOD_V6_PATH)"

run-v7:
	"$(GODOT)" --path "$(GOD_V7_PATH)"

run-v8:
	"$(GODOT)" --path "$(GOD_V8_PATH)"

run-v9:
	"$(GODOT)" --path "$(GOD_V9_PATH)"

run-v10:
	"$(GODOT)" --path "$(GOD_V10_PATH)"

run-v11:
	"$(GODOT)" --path "$(GOD_V11_PATH)"

run-v12:
	"$(GODOT)" --path "$(GOD_V12_PATH)"

run-v13:
	"$(GODOT)" --path "$(GOD_V13_PATH)"

run-v14:
	"$(GODOT)" --path "$(GOD_V14_PATH)"
