#!/usr/bin/env python3

from __future__ import annotations

import argparse
import base64
import os
from pathlib import Path
from typing import Any
from urllib.request import urlopen

from asset_prompt_builder import build_asset_id, load_spec
from pipeline_common import (
    GAME_ASSETS_DIR,
    SOURCE_DIR,
    load_env_file,
    load_json,
    merge_unique,
    parse_prompt_file,
    prompt_file_paths,
    utc_now_iso,
    write_json,
)


RAW_IMAGE_ROOT = SOURCE_DIR / "generated" / "images" / "raw"


def load_openai_client():
    try:
        from openai import OpenAI
    except ImportError as exc:
        raise SystemExit(
            "The 'openai' package is not installed. Run 'make install-tools' first."
        ) from exc
    return OpenAI()


def read_plan(plan_path: Path) -> list[dict]:
    payload = load_json(plan_path)
    if not isinstance(payload, list):
        raise SystemExit(f"Expected prompt plan list: {plan_path}")
    return payload


def decode_image_payload(item: Any) -> bytes:
    b64_value = getattr(item, "b64_json", None)
    if not b64_value and isinstance(item, dict):
        b64_value = item.get("b64_json")
    if b64_value:
        return base64.b64decode(b64_value)

    url_value = getattr(item, "url", None)
    if not url_value and isinstance(item, dict):
        url_value = item.get("url")
    if url_value:
        with urlopen(url_value) as response:
            return response.read()

    raise SystemExit("OpenAI image response did not contain b64_json or url output.")


def select_entries(entries: list[dict], animation: str | None, direction: str | None, limit: int | None) -> list[dict]:
    selected = []
    for entry in entries:
        if animation and entry.get("animation") != animation:
            continue
        if direction and entry.get("direction") != direction:
            continue
        selected.append(entry)
        if limit and len(selected) >= limit:
            break
    return selected


def update_manifest(
    manifest_path: Path,
    generated_items: list[dict],
    model: str,
    size: str,
    quality: str,
    background: str,
) -> None:
    manifest = load_json(manifest_path)
    if not isinstance(manifest, dict):
        raise SystemExit(f"Expected manifest object: {manifest_path}")

    manifest["tool"] = "openai"
    manifest["model"] = model
    manifest.setdefault("generated_outputs", [])

    for item in generated_items:
        manifest["generated_outputs"] = merge_unique(manifest["generated_outputs"], item)

    manifest["notes"] = (
        "Generated by tools/asset_prompt_builder.py and tools/generate_images.py "
        f"with size={size}, quality={quality}, background={background}"
    )
    write_json(manifest_path, manifest)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate raw images from an asset prompt plan using OpenAI.")
    parser.add_argument("spec", help="Path to the asset spec JSON file.")
    parser.add_argument("--animation", help="Filter to one animation.")
    parser.add_argument("--direction", help="Filter to one direction.")
    parser.add_argument("--limit", type=int, help="Limit the number of generated frames.")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be generated without calling OpenAI.")
    parser.add_argument("--model", help="Override image generation model.")
    parser.add_argument("--size", help="Override image size.")
    parser.add_argument("--quality", help="Override image quality.")
    parser.add_argument("--background", help="Override background mode.")
    parser.add_argument("--moderation", help="Override moderation level.")
    args = parser.parse_args()

    load_env_file()

    spec_path = Path(args.spec)
    spec = load_spec(spec_path)
    asset_id = build_asset_id(spec)
    prompt_path, plan_path, manifest_path = prompt_file_paths(asset_id)
    if not prompt_path.exists() or not plan_path.exists() or not manifest_path.exists():
        raise SystemExit(
            "Prompt plan or manifest missing. Run tools/asset_prompt_builder.py for this spec first."
        )

    _, negative_prompt = parse_prompt_file(prompt_path)
    entries = read_plan(plan_path)
    selected_entries = select_entries(entries, args.animation, args.direction, args.limit)
    if not selected_entries:
        raise SystemExit("No prompt plan entries matched the requested filters.")

    model = args.model or os.environ.get("OPENAI_IMAGE_MODEL", "gpt-image-1.5")
    size = args.size or os.environ.get("OPENAI_IMAGE_SIZE", "1024x1024")
    quality = args.quality or os.environ.get("OPENAI_IMAGE_QUALITY", "medium")
    background = args.background or os.environ.get("OPENAI_IMAGE_BACKGROUND", "transparent")
    moderation = args.moderation or os.environ.get("OPENAI_IMAGE_MODERATION", "auto")

    if args.dry_run:
        for entry in selected_entries:
            target_path = RAW_IMAGE_ROOT / asset_id / entry["filename"]
            print(f"DRY RUN {entry['animation']} {entry['direction']} frame={entry['frame_index']} -> {target_path}")
            print(f"PROMPT: {entry['prompt']}")
            if negative_prompt:
                print(f"NEGATIVE: {negative_prompt}")
        return 0

    client = load_openai_client()
    generated_items = []
    for entry in selected_entries:
        output_path = RAW_IMAGE_ROOT / asset_id / entry["filename"]
        output_path.parent.mkdir(parents=True, exist_ok=True)
        request_prompt = entry["prompt"]
        if negative_prompt:
            request_prompt = f"{request_prompt}. Avoid: {negative_prompt}."

        result = client.images.generate(
            model=model,
            prompt=request_prompt,
            size=size,
            quality=quality,
            background=background,
            moderation=moderation,
        )
        image_bytes = decode_image_payload(result.data[0])
        output_path.write_bytes(image_bytes)

        generated_items.append(
            {
                "path": str(output_path.relative_to(GAME_ASSETS_DIR.parent)).replace("\\", "/"),
                "animation": entry["animation"],
                "direction": entry["direction"],
                "frame_index": entry["frame_index"],
                "model": model,
                "size": size,
                "quality": quality,
                "background": background,
                "prompt": request_prompt,
                "generated_at": utc_now_iso(),
            }
        )
        print(f"generated={output_path}")

    update_manifest(manifest_path, generated_items, model, size, quality, background)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
